const columns = {
    
    Id:"Store code",
    Store_Name:"Store name",
    Store_Type_1:"Retail chain",
    Store_Type_2: "Retail chain",
    Brands:"Brand(s) sold in the retail chain",
    Store_Address_1:"First address line of the store account postal address",
    Store_Address_2:"Second address line of the store account postal address",
    Store_City:"City of the store",
    Store_Postal_Code:"Store postal code",
    Store_Country_Code:"Store country code",
    Latitude:"Store latitude",
    Longitude:"Store longitude",
    Total_Openings_Hours:"Store total weekly opening hours",
    Total_Openings_Holidays_Hours:"Store total weekly opening hours during holidays",
    Monday_Start:"Opening time on Monday",
    Monday_End:"Closing time on Monday",
    Monday_Hours:"Opening hours on Monday",
    Monday_Is_Closed:"Store closed on Monday",
    Tuesday_Start:"Opening time on Tuesday",
    Tuesday_End:"Closing time on Tuesday",
    Tuesday_Hours:"Opening hours on Tuesday",
    Tuesday_Is_Closed:"Store closed on Tuesday",
    Wednesday_Start:"Opening time on Wednesday",
    Wednesday_End:"Closing time on Wednesday",
    Wednesday_Hours:"Opening hours on Wednesday",
    Wednesday_Is_Closed:"Store closed on Wednesday",
    Thursday_Start:"Opening time on Thursday",
    Thursday_End:"Closing time on Thursday",
    Thursday_Hours:"DECIMAL	YES	Opening hours on Thursday",
    Thursday_Is_Closed:"Store closed on Thursday",
    Friday_Start:"Opening time on Friday",
    Friday_End:"Closing time on Friday",
    Friday_Hours:"Opening hours on Friday",
    Friday_Is_Closed:"Store closed on Friday",
    Saturday_Start:"Opening time on Saturday",
    Saturday_End:"Closing time on Saturday",
    Saturday_Hours:"Opening hours on Saturday",
    Saturday_Is_Closed:"Store closed on Saturday",
    Sunday_Start:"Opening time on Sunday",
    Sunday_End:"Closing time on Sunday",
    Sunday_Hours:"Opening hours on Sunday",
    Sunday_Is_Closed:"Store closed on Sunday",
    Holidays_Start:"Holidays opening time",
    Holidays_End:"Holidays closing time",
    Holidays_Hours:"Opening hours during holidays",
    Holidays_Is_Closed:"Store closed during holidays",
    Store_Is_Closed:"Store closed",
    Phone:"Store phone number",
    Email_Store:"Store email address",
    Timezone:"Store time zone",
    Region_Code:"Store region code",
    Click_Collect:"Click and collect availablilty",	
    Parking:"Parking availablilty",
    Wheelchair_Entrance:"Wheelchair entrance availablilty",	
    Downtown:"Store location",
    Adyen_Merchant_Account:"Payment processing merchant identification number",
    Email_Region_Director:"Region director email address",
    Ois_Active:"Order in store active",
    Ereservation:"Ereservation active",
    Store_Priority_Code:"Store priority code",
    Ship_From_Store:"Ship from store active",
    Store_Priority:"STRING	YES	Store priority",
    Outlet_Store:"Is the store an outlet store"
};
module.exports = {columns} ;